language: swift
osx_image: xcode12.2
env:
  global:
    - CI_BUILD_NUMBER=${TRAVIS_BUILD_NUMBER}
before_install:
  - bundle install
  - bundle exec pod install
  
jobs:
  include:
    - stage: "Build"
      name: "Build internal app"
      script:
        - set -o pipefail
        - echo "machine github.com login $GITHUB_API_TOKEN" >> ~/.netrc
        - bundle exec fastlane download_profiles
        - bundle exec fastlane archive_internal

    - stage: "Test"
      name: "Test app"
      script:
        - set -o pipefail
        - bundle exec fastlane tests
  
    - stage: "Archive, sign and deploy internal app"
      name: "Archive Internal app"
      if: branch = main
      script:
        - set -o pipefail
        - echo "machine github.com login $GITHUB_API_TOKEN" >> ~/.netrc
        - bundle exec fastlane download_profiles
        - ./scripts/increment_build_number.sh
        - bundle exec fastlane archive_internal
        - bundle exec fastlane upload_symbols_to_crashlytics_internal
        - bundle exec fastlane deploy_internal
        
    - stage: "Archive, sign and deploy production app"
      name: "Archive Production app"
      if: branch = main # usually use `if: branch = release`
      script:
        - set -o pipefail
        - echo "machine github.com login $GITHUB_API_TOKEN" >> ~/.netrc
        - bundle exec fastlane download_profiles
        - ./scripts/increment_build_number.sh
        - bundle exec fastlane archive_appstore
        - bundle exec fastlane upload_symbols_to_crashlytics_appstore
        - bundle exec fastlane deploy_appstore

after_success:
  - sleep 5 # Workaround for https://github.com/travis-ci/travis-ci/issues/4725
