source 'https://cdn.cocoapods.org/'

#workspace './Moments.xcworkspace'
#project './Moments/Moments.xcodeproj'
inhibit_all_warnings!

platform :ios, '14.0'
use_frameworks!



target 'Demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Demo
 pod 'RxSwift'

end
