source 'https://cdn.cocoapods.org/'

#workspace './Demo.xcworkspace'
#project './Demo.xcodeproj'
inhibit_all_warnings!

platform :ios, '14.0'
use_frameworks!



target 'Demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Demo
 pod 'RxSwift'
 pod 'SwiftLint'

end
